" Copyright 2024 dah4k
" SPDX-License-Identifier: MIT-0

" General Settings
set nocompatible
set backspace=2
set encoding=utf-8
filetype on

" Disable borken mouse
set mouse=""

" Visual Settings
syntax clear
syntax on
set ruler
set number
set hlsearch

" 4-space indent
set tabstop=4
set softtabstop=0
set shiftwidth=4
set expandtab

" Trim trailing whitespaces while preserving current view
" Credit: ThePrimeagen
function! TrimWhitespace()
    let l:save = winsaveview()
    keeppatterns %s/\s\+$//e
    call winrestview(l:save)
endfunction
autocmd BufWritePre * call TrimWhitespace()

" Mappings
cnoreabbrev w1 w!
nnoremap ; :
vnoremap ; :
nnoremap <F6> :bprevious<CR>
nnoremap <F7> :bnext<CR>
